stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

cache:
  paths:
    - .m2/repository

test:
  stage: test
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - ./run_tests.sh
  artifacts:
    when: always
    reports:
      junit: eitimoto-backend/target/surefire-reports/TEST-*.xml
