services:
  db:
    image: pgvector/pgvector:pg16
    ports:
      - "3001:5432"
    restart: always
    environment:
      POSTGRES_DB: eitimoto_db
      POSTGRES_USER: eitimoto_user
      POSTGRES_PASSWORD: zawszemoznapytac
  backend:
    build: ./eitimoto-backend
    ports:
      - "3333:3333"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/eitimoto_db
      SPRING_DATASOURCE_USERNAME: eitimoto_user
      SPRING_DATASOURCE_PASSWORD: zawszemoznapytac
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend
