spring.application.name=eitimoto-backend
server.port=3333

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:3000/eitimoto_db
spring.datasource.username=eitimoto_user
spring.datasource.password=zawszemoznapytac
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


