services:
  db:
    image: postgres:latest
    ports:
      - "3000:5432"
    restart: always
    environment:
      POSTGRES_DB: eitimoto_db
      POSTGRES_USER: eitimoto_user
      POSTGRES_PASSWORD: zawszemoznapytac
