-- Enable Postgres compatibility modes if not fully covered by connection string
SET MODE PostgreSQL;

-- Mock vector type for H2 to avoid errors with ?::vector casting if possible,
-- or at least allow the table creation.
-- H2 doesn't support the 'vector' type natively.
-- define a domain or alias if possible, but 'vector(1536)' is a parameterized type which is hard to alias in H2.
-- We'll try to use ARRAY or simple column for it.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    contact_number VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    role VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS car (
     car_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     car_brand VARCHAR(255) NOT NULL,
     car_model VARCHAR(255) NOT NULL,
     car_body_type VARCHAR(255) NOT NULL,
     production_year INTEGER NOT NULL,
     price INTEGER NOT NULL,
     mileage INTEGER NOT NULL,
     fuel_type VARCHAR(255) NOT NULL,
     transmission VARCHAR(255) NOT NULL,
     power INTEGER NOT NULL,
     car_color VARCHAR(255) NOT NULL,
     engine_capacity DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS advertisement (
    advertisement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255),
    car_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    view_count BIGINT DEFAULT 0,
    contact_count BIGINT DEFAULT 0,
    like_count BIGINT DEFAULT 0,
    image BINARY, -- or VARBINARY, H2 supports usage of `bytea` in pg mode too
    embedding OTHER, -- Using OTHER to mock vector.
    CONSTRAINT fk_ad_car FOREIGN KEY (car_id) REFERENCES car(car_id),
    CONSTRAINT fk_ad_user_id FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS comment (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(255),
    created_at TIMESTAMP,
    user_id BIGINT,
    advertisement_id BIGINT,
    CONSTRAINT fk_comment_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_comment_ad FOREIGN KEY (advertisement_id) REFERENCES advertisement(advertisement_id)
);

CREATE TABLE IF NOT EXISTS brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE,
    logo_url VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS car_models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    photo_url VARCHAR(255),
    production_year_start INTEGER,
    production_year_end INTEGER,
    engine_type VARCHAR(255),
    horse_power INTEGER,
    brand_id BIGINT,
    CONSTRAINT fk_model_brand FOREIGN KEY (brand_id) REFERENCES brands(id)
);

CREATE TABLE IF NOT EXISTS favorite_advertisement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    advertisement_id BIGINT NOT NULL,
    CONSTRAINT fk_fav_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_fav_ad FOREIGN KEY (advertisement_id) REFERENCES advertisement(advertisement_id)
);
